<a href="https://colab.research.google.com/github/EAFIT-BI/BI-Introduction-2024-1/blob/main/Gesti%C3%B3n_con_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gestión de bases de datos con SQL

SQL es un lenguaje que nos permite gestionar la información que se encuentra en diversas bases de datos. El motor para trabajar con SQL en Python es `sqlite`, sin embargo, los gestores por excelencia son `SQL Server` y `MySQL`

In [ ]:
#como primer paso, cargamos la tabla con la información original

#importamos las libererías necesarias
import pandas as pd
import sqlite3

#cargamos la información en la variable datos
datos = pd.read_csv("/content/Clientes.csv")

#visualizamos los primeros registros
datos

,IdCliente,Apellido,Nombre,Dirección,Ciudad,IdOrden,FechaOrden,CanalCompra,MetodoPago,CantProductos,IdProducto,NombreProducto,CategoriaProducto,Peso,Precio
0,1,García,Juan,Calle 123,Ciudad A,1001,2024-01-01,Tienda,Tarjeta,2,101,Manzanas,Frutas,2 kg,$5.00
1,2,López,María,Av. Principal 456,Ciudad B,1002,2024-01-02,Online,PayPal,3,102,Zanahorias,Verduras,1 kg,$3.00
2,3,Pérez,Luisa,Calle Central 789,Ciudad C,1003,2024-01-03,Tienda,Efectivo,1,103,Lechuga,Verduras,500 g,$2.50
3,4,Martínez,Ana,Av. Libertador 321,Ciudad A,1004,2024-01-04,Tienda,Tarjeta,2,104,Fresas,Frutas,1 kg,$4.00
4,5,Rodríguez,Carlos,Calle 567,Ciudad B,1005,2024-01-05,Online,PayPal,1,105,Espinacas,Verduras,500 g,$3.00
5,6,Sánchez,Laura,Calle 890,Ciudad C,1006,2024-01-06,Tienda,Efectivo,2,106,Peras,Frutas,2 kg,$5.50
6,7,González,Roberto,Av. Independencia,Ciudad A,1007,2024-01-07,Tienda,Efectivo,3,107,Plátanos,Frutas,3 kg,$6.00
7,8,Díaz,Sofia,Calle 444,Ciudad B,1008,2024-01-08,Online,Tarjeta,1,108,Pimientos,Verduras,500 g,$4.00
8,9,Vásquez,Alejandro,Calle 999,Ciudad C,1009,2024-01-09,Tienda,Efectivo,2,109,Uvas,Frutas,1.5 kg,$7.00
9,10,Fernández,Andrea,Av. Principal 123,Ciudad A,1010,2024-01-10,Online,PayPal,2,110,Pepinos,Verduras,1 kg,$3.50
10,1,García,Juan,Calle 123,Ciudad A,1021,2024-01-21,Online,PayPal,3,121,Tomates,Verduras,1 kg,$4.00
11,2,López,María,Av. Principal 456,Ciudad B,1022,2024-01-22,Tienda,Efectivo,1,112,Berenjenas,Verduras,750 g,$3.00
12,3,Pérez,Luisa,Calle Central 789,Ciudad C,1023,2024-01-23,Online,Tarjeta,2,113,Naranjas,Frutas,1 kg,$4.50
13,4,Martínez,Ana,Av. Libertador 321,Ciudad A,1024,2024-01-24,Tienda,Efectivo,1,114,Sandías,Frutas,3 kg,$8.00
14,5,Rodríguez,Carlos,Calle 567,Ciudad B,1025,2024-01-25,Online,PayPal,4,115,Papayas,Frutas,2 kg,$6.00
15,6,Sánchez,Laura,Calle 890,Ciudad C,1026,2024-01-26,Tienda,Tarjeta,2,116,Espárragos,Verduras,500 g,$4.00
16,7,González,Roberto,Av. Independencia,Ciudad A,1027,2024-01-27,Online,Efectivo,3,117,Melones,Frutas,2 kg,$7.50
17,8,Díaz,Sofia,Calle 444,Ciudad B,1028,2024-01-28,Tienda,PayPal,1,118,Cerezas,Frutas,500 g,$5.00
18,9,Vásquez,Alejandro,Calle 999,Ciudad C,1029,2024-01-29,Online,Tarjeta,2,119,Limones,Frutas,1 kg,$3.00
19,10,Fernández,Andrea,Av. Principal 123,Ciudad A,1030,2024-01-30,Tienda,Efectivo,3,120,Uvas,Frutas,1.5 kg,$7.00

In [ ]:
import numpy as np
np.unique(datos['IdCliente'])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#como segundo paso, creamos la base de datos de interés

#creamos el conector a la base de datos

conn = sqlite3.connect('fruver.db')

In [ ]:
#como tercer paso, creamos las tablas de acuerdo a nuestro modelo entidad-relación

#creamos la tabla CLIENTE

#definimos la consulta
crear_tabla_cliente = '''CREATE TABLE IF NOT EXISTS CLIENTE(
  IdCliente INTEGER PRIMARY KEY,
  Apellido TEXT,
  Nombre TEXT,
  Dirección TEXT,
  Ciudad TEXT
)'''

#creamos un apuntador a la base de datos (cursor)
apuntador = conn.cursor()

#ejecuto el query o la consulta
apuntador.execute(crear_tabla_cliente)

#hacemos commit sobre la conexión
conn.commit()

In [ ]:
#como cuarto punto, pasamos la información del DataFrame a la tabla CLIENTE

#definimos la información que queremos pasar
datos_cliente = datos[['IdCliente', 'Apellido', 'Nombre', 'Dirección', 'Ciudad']]
#tomamos solo los 10 primeros clientes porque los otros 10 son repetición.
#de esta forma aseguramos el identificador único
datos_cliente = datos_cliente[0:10]

#hacemos el transpaso de la información
datos_cliente.to_sql('CLIENTE', conn, if_exists = 'append', index = False)

10

In [ ]:
#como último paso, visualizamos la información de la tabla CLIENTE, para efectos de comprobamos

#creamos la consulta o el query para traer la información de la tabla
consulta = '''SELECT * FROM CLIENTE'''

#ejecutamos la consulta
apuntador.execute(consulta)

#obtenemos los resultados de la consulta
resultado = apuntador.fetchall()

#mostramos el resultado
#print(resultado)

#mostramos el resultado, que es una lista de tuplas, en forma organizada
for filas in resultado:
  print(filas)

(1, 'García', 'Juan', 'Calle 123', 'Ciudad A')
(2, 'López', 'María', 'Av. Principal 456', 'Ciudad B')
(3, 'Pérez', 'Luisa', 'Calle Central 789', 'Ciudad C')
(4, 'Martínez', 'Ana', 'Av. Libertador 321', 'Ciudad A')
(5, 'Rodríguez', 'Carlos', 'Calle 567', 'Ciudad B')
(6, 'Sánchez', 'Laura', 'Calle 890', 'Ciudad C')
(7, 'González', 'Roberto', 'Av. Independencia', 'Ciudad A')
(8, 'Díaz', 'Sofia', 'Calle 444', 'Ciudad B')
(9, 'Vásquez', 'Alejandro', 'Calle 999', 'Ciudad C')
(10, 'Fernández', 'Andrea', 'Av. Principal 123', 'Ciudad A')

In [ ]:
#repetimos los pasos anteriores para las tablas COMPRA y PRODUCTO

#para la tabla COMPRA:

#definimos la consulta
crear_tabla_compra = '''CREATE TABLE IF NOT EXISTS COMPRA(
  IdOrden INTEGER PRIMARY KEY,
  FechaOrden DATE,
  CanalCompra TEXT,
  MetodoPago TEXT,
  IdCliente INTEGER,
  FOREIGN KEY(IdCliente) REFERENCES CLIENTE('IdCliente'))'''

#creamos un apuntador a la base de datos (cursor)
apuntador = conn.cursor()

#ejecuto el query o la consulta
apuntador.execute(crear_tabla_compra)

#hacemos commit sobre la conexión
conn.commit()

#como cuarto punto, pasamos la información del DataFrame a la tabla COMPRA

#definimos la información que queremos pasar
datos_compra = datos[['IdOrden', 'FechaOrden', 'CanalCompra', 'MetodoPago', 'IdCliente']]

#hacemos el transpaso de la información
datos_compra.to_sql('COMPRA', conn, if_exists = 'append', index = False)

20

In [ ]:
#como último paso, visualizamos la información de la tabla CLIENTE, para efectos de comprobamos

#creamos la consulta o el query para traer la información de la tabla
consulta = '''SELECT * FROM COMPRA'''

#ejecutamos la consulta
apuntador.execute(consulta)

#obtenemos los resultados de la consulta
resultado = apuntador.fetchall()

#mostramos el resultado, que es una lista de tuplas, en forma organizada
for filas in resultado:
  print(filas)

(1001, '2024-01-01', 'Tienda', 'Tarjeta', 1)
(1002, '2024-01-02', 'Online', 'PayPal', 2)
(1003, '2024-01-03', 'Tienda', 'Efectivo', 3)
(1004, '2024-01-04', 'Tienda', 'Tarjeta', 4)
(1005, '2024-01-05', 'Online', 'PayPal', 5)
(1006, '2024-01-06', 'Tienda', 'Efectivo', 6)
(1007, '2024-01-07', 'Tienda', 'Efectivo', 7)
(1008, '2024-01-08', 'Online', 'Tarjeta', 8)
(1009, '2024-01-09', 'Tienda', 'Efectivo', 9)
(1010, '2024-01-10', 'Online', 'PayPal', 10)
(1021, '2024-01-21', 'Online', 'PayPal', 1)
(1022, '2024-01-22', 'Tienda', 'Efectivo', 2)
(1023, '2024-01-23', 'Online', 'Tarjeta', 3)
(1024, '2024-01-24', 'Tienda', 'Efectivo', 4)
(1025, '2024-01-25', 'Online', 'PayPal', 5)
(1026, '2024-01-26', 'Tienda', 'Tarjeta', 6)
(1027, '2024-01-27', 'Online', 'Efectivo', 7)
(1028, '2024-01-28', 'Tienda', 'PayPal', 8)
(1029, '2024-01-29', 'Online', 'Tarjeta', 9)
(1030, '2024-01-30', 'Tienda', 'Efectivo', 10)

In [ ]:
# Para la tabla PRODUCTO

#definimos la consulta
crear_tabla_producto = '''CREATE TABLE IF NOT EXISTS PRODUCTO(
  IdProducto INTEGER PRIMARY KEY,
  CantProductos INTEGER,
  NombreProducto TEXT,
  CategoriaProducto TEXT,
  Peso FLOAT,
  Precio FLOAT,
  IdOrden INTEGER,
  FOREIGN KEY(IdOrden) REFERENCES COMPRA(IdOrden))'''

#creamos un apuntador a la base de datos (cursor)
apuntador = conn.cursor()

#ejecuto el query o la consulta
apuntador.execute(crear_tabla_producto)

#hacemos commit sobre la conexión
conn.commit()

#como cuarto punto, pasamos la información del DataFrame a la tabla PRODUCTO

#definimos la información que queremos pasar
datos_producto = datos[['IdProducto', 'CantProductos', 'NombreProducto', 'CategoriaProducto', 'Peso',
                        'Precio', 'IdOrden']]

#hacemos el transpaso de la información
datos_producto.to_sql('PRODUCTO', conn, if_exists = 'append', index = False)

20